name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install yarn dependencies
        run: yarn install --frozen-lockfile

      - name: lint
        run: yarn lint

      - name: test
        run: yarn test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5

      - name: build
        run: yarn build
